about/urls.py
from django.urls import path

from about.views import about

app_name = 'about'

urlpatterns = [
    path('', about, name='about'), #!
]

contacts/urls.py
from django.urls import path

from contacts.views import contacts

app_name = 'contacts'

urlpatterns = [
    path('', contacts, name='contacts'), #!
]

product/urls.py
from django.urls import path, include

from product.views import product, basket_add, basket_delete, search, product_details, privacy, checkout

app_name = 'product'

urlpatterns = [
    path('', product, name='index'),
    path('search/', search, name='search'),
    path('category/<int:category_id>/', product, name='category'),
    path('page/<int:page>/', product, name='page'),
    path('brand/<str:brand>/', product, name='brand'),
    path('country/<str:country>/', product, name='country'),
    path('material/<str:material>/', product, name='material'),
    path('sort/<str:sort>/', product, name='sort'),
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete'),
    path('checkout/', checkout, name='checkout'),
    path('details/<int:prod_id>/', product_details, name='product_details'),

]

users/urls.py
from django.urls import path

from users.views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
]

product/models.py
from django.db import models

from users.models import User


# Create your models here.
# Модели = таблици БД

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    image = models.ImageField(upload_to='product_images', blank=True)
    image1 = models.ImageField(upload_to='product_images', blank=True)
    image2 = models.ImageField(upload_to='product_images', blank=True)
    image3 = models.ImageField(upload_to='product_images', blank=True)
    name = models.CharField(max_length=256)
    price = models.IntegerField(default=0)
    product_code = models.IntegerField(default=0)
    exist = models.BooleanField(default=False)
    description = models.TextField(blank=True)
    country = models.CharField(max_length=64, blank=True)
    brand_name = models.CharField(max_length=64, blank=True)
    gender = models.CharField(max_length=12, blank=True)
    mechanism = models.CharField(max_length=64, blank=True)
    case_material = models.CharField(max_length=64, blank=True)
    waterproof = models.CharField(max_length=64, blank=True)
    warranty = models.CharField(max_length=64, blank=True, default=12)
    quantity = models.PositiveIntegerField(default=0)

    category = models.ForeignKey(ProductCategory, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ['id']

    def __str__(self):
        return f'{self.name} | {self.category.name}'


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price


class FilterBrand(models.Model):
    brand = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = 'Brand filter'

    def __str__(self):
        return self.brand


class FilterCountry(models.Model):
    country = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = 'Country filter'

    def __str__(self):
        return self.country


class FilterMaterial(models.Model):
    material = models.CharField(max_length=64)

    class Meta:
        verbose_name_plural = 'Material filter'

    def __str__(self):
        return self.material

product/views.py
from django.views.generic import ListView, TemplateView

from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.urls import reverse

from product.models import ProductCategory, Product, Basket, FilterBrand, FilterCountry, FilterMaterial


def index(request):
    context = {
        'title': 'Главная',
        'products': Product.objects.all()[:3],
    }

    return render(request, 'product/index.html', context)


def product(request, category_id=None, page=1, brand=None, country=None, material=None, sort=None):
    q = request.GET.get('q')
    context = {
        'title': 'Каталог',
        'categories': ProductCategory.objects.all(),
        'filter_by_brand': FilterBrand.objects.order_by('brand'),
        'filter_by_country': FilterCountry.objects.order_by('country'),
        'filter_by_material': FilterMaterial.objects.order_by('material'),
    }
    if q:
        products = Product.objects.filter(name__icontains=q)
    elif category_id:
        products = Product.objects.filter(category_id=category_id)
    elif country:
        products = Product.objects.filter(country=country)
    elif brand:
        products = Product.objects.filter(brand_name=brand)
    elif material:
        products = Product.objects.filter(case_material=material)
    elif sort:
        if sort == "cheaper":
            products = Product.objects.order_by('price')
        elif sort == "expensive":
            products = Product.objects.order_by('-price')
    else:
        products = Product.objects.all()
    paginator = Paginator(products, 9)
    product_paginator = paginator.page(page)
    context.update({'products': product_paginator})

    return render(request, 'product/products.html', context)


@login_required
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def checkout(request):
    basket = Basket.objects.all()
    basket.delete()

    return render(request, 'product/thanks.html')


def search(request):
    search_query = request.GET.get('search')
    context = {
        'products': Product.objects.filter(name__icontains=search_query),
        'search': search_query
    }

    return render(request, 'product/products.html', context)


def product_details(request, prod_id=None):
    context = {
        'title': 'Товар',
        'product_detail': Product.objects.get(id=prod_id),
    }

    context['products'] = Product.objects.filter(case_material=context['product_detail'].case_material)
    context['length'] = len(context['products'])

    return render(request, 'product/product_details.html', context)


def privacy(request):
    return render(request, 'product/privacy_policy.html')

product/templates/product/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>
    <script type="text/javascript" src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>

    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">

    <!-- FontAwesome script -->
    <script src="https://kit.fontawesome.com/40df351620.js" crossorigin="anonymous"></script>

    <!-- Slick -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick-theme.css' %}">

    {% block css %} {% endblock %}
</head>

<body>
<!--     Start Top Nav-->
<nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
    <div class="container text-light">
        <div class="w-100 d-flex justify-content-between">
            <div>
                <i class="fa fa-envelope mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:xwins2000@gmail.com">xwins2000@gmail.com</a>
                <i class="fa fa-phone mx-2"></i>
                <a class="navbar-sm-brand text-light text-decoration-none" href="tel:+3809999999">+38 (099)
                    99-99-999</a>
            </div>
            <div>
                <a class="text-light" href="https://fb.com/" target="_blank" rel="sponsored"><i
                        class="fab fa-facebook-f fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.instagram.com/" target="_blank"><i
                        class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://twitter.com/" target="_blank"><i
                        class="fab fa-twitter fa-sm fa-fw me-2"></i></a>
                <a class="text-light" href="https://www.linkedin.com/" target="_blank"><i
                        class="fab fa-linkedin fa-sm fa-fw"></i></a>
            </div>
        </div>
    </div>
</nav>
<!--     Close Top Nav -->
<!-- Header -->
<nav class="navbar navbar-expand-lg navbar-light shadow">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'assets/img/logo.jpg'%}" alt="" width="25" height="25"
                 class="d-inline-block align-text-top">
        </a>
        <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between"
             id="templatemo_main_nav">
            <div class="flex-fill">
                <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'product:index' %}">Каталог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about:about' %}">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contacts:contacts' %}">Контакты</a>
                    </li>
                </ul>
            </div>
            <div class="navbar align-self-center d-flex">
                <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                    <div class="input-group">
                        <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                        <div class="input-group-text">
                            <i class="fa fa-fw fa-search"></i>
                        </div>
                    </div>
                </div>
                <a class="nav-icon d-none d-lg-inline" href="{% url 'product:search' %}" data-bs-toggle="modal"
                   data-bs-target="#templatemo_search">
                    <i class="fa fa-fw fa-search text-dark mr-2"></i>
                </a>
                <ul class="navbar-nav ml-auto h6">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}"> {{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}"><i class="fas fa-sign-in-alt"></i></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

    </div>
</nav>
<!-- Close Header -->
<!-- Modal -->
<div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="w-100 pt-1 mb-5 text-right">
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'product:search' %}" method="get" class="modal-content modal-body border-0 p-0">
            <div class="input-group mb-2">
                <input type="text" class="form-control" id="inputModalSearch" name="search" placeholder="Search ...">
                <button type="submit" class="input-group-text bg-success text-light">
                    <i class="fa fa-fw fa-search text-white"></i>
                </button>
            </div>
        </form>
    </div>
</div>
<!-- Page Content -->
{% block content %} {% endblock %}

<footer class="bg-dark text-white">
    <!-- Grid container -->
    <div class="container p-4 pb-4">
        <div class="row d-flex">
            <div class="col-auto me-auto">
                <i class="fa-brands fa-google-pay fa-2x"></i>
                <i class="fa-brands fa-cc-visa fa-2x ps-3"></i>
                <i class="fa-brands fa-apple-pay fa-2x ps-3"></i>
                <i class="fa-brands fa-cc-mastercard fa-2x ps-3"></i>
            </div>
            <!--Grid column-->
            <div class="col-auto ms-auto">
                <a href="{% url 'privacy' %}" style="text-decoration: none;"
                   class="text-light fs-6" target="_blank">Пользовательское соглашение</a>
            </div>
        </div>
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        Copyright &copy; 2021 |
        <a class="text-white" href="https://github.com/MultiMilli" target="_blank">MultiMilli</a>
    </div>
    <!-- Copyright -->
</footer>

<!-- End of container -->
<!-- End Footer -->

<!-- Start Script -->
<script src="{% static 'assets/js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/templatemo.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<!-- End Script -->

{% block js %} {% endblock %}

</body>
</html>

product/templates/product/basket.html
{% if baskets %}
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center ">
        Корзина <span class="badge badge-secondary badge-pill"> {{ total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ basket.product.name }}</h5>
            <p class="card-text">{{ basket.product.brand }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                <span class="text-muted">{{ basket.quantity }} шт. </span>
                <span class="text-muted">{{ basket.sum }} грн. </span>
                <span class="text-muted">
                    <a href="{% url 'product:basket_add' basket.product.id %}"
                       style=" color: gray;">
                        <i class="fas fa-cart-plus"></i>
                    </a>
                    <a href="{% url 'product:basket_delete' basket.id %}" style="color: gray;">
                        <i class="far fa-trash-alt"></i>
                    </a>
                </span>
            </li>
        </ul>
    </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого:</p>
            <h4 class="float-right">{{ total_sum }} грн.</h4>
        </div>
    </div>
    <a href="{% url 'product:checkout' %}" class="btn btn-success btn-lg" role="button">
        <strong>Оформить</strong>
    </a>
</div>
{% else %}
<div class="col-lg-5">
    <h4 class="mt-3 mb-3 text-center"> Корзина пуста! </h4>
    <h5 class="mt-3 mb-3 text-center"> Добавьте интересующий товар -
        <a href="{% url 'product:index' %}" style="color: black;">
            <i class="fa-solid fa-cart-arrow-down"></i>
        </a>
    </h5>

</div>
{% endif %}

product/templates/product/products.html
{% extends 'product/base.html' %}
{% load static %}

{% block css %} {% endblock %}

{% block content %}
<!-- Start Content -->
{% if products %}
<div class="container py-5">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="h2 pb-4">Категории</h1>
            <ul class="list-unstyled templatemo-accordion">
                <li class="pb-3">
                    <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                        Бренд
                        <i class="fa fa-fw fa-chevron-circle-down mt-1"></i>
                    </a>
                    <ul class="collapse show list-unstyled pl-3">
                        {% for filter in filter_by_brand %}
                        <li><a class="text-decoration-none" href="{% url 'product:brand' filter.brand %}">{{ filter.brand }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="pb-3">
                    <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                        Страна
                        <i class="pull-right fa fa-fw fa-chevron-circle-down mt-1"></i>
                    </a>
                    <ul id="collapseTwo" class="collapse list-unstyled pl-3">
                        {% for filter in filter_by_country %}
                        <li><a class="text-decoration-none" href="{% url 'product:country' filter.country %}">{{ filter.country }}</a></li>
                        {% endfor %}

                    </ul>
                </li>
                <li class="pb-3">
                    <a class="collapsed d-flex justify-content-between h3 text-decoration-none" href="#">
                        Материал
                        <i class="pull-right fa fa-fw fa-chevron-circle-down mt-1"></i>
                    </a>
                    <ul id="collapseThree" class="collapse list-unstyled pl-3">
                        {% for filter in filter_by_material %}
                        <li><a class="text-decoration-none" href="{% url 'product:material' filter.material %}">{{ filter.material}} </a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-lg-9">
            <div class="row">
                <div class="text-end">
                    <ul class="list-inline shop-top-menu pb-3 pt-1">
                        <li class="list-inline-item">
                            <a class="fs-6 text-dark text-decoration-none mr-3" href="{% url 'product:index' %}">ВСЕ</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="fs-6 text-dark text-decoration-none mr-3 "
                               href="{% url 'product:category' category_id=1 %}">МУЖСКИЕ</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="fs-6 text-dark text-decoration-none"
                               href="{% url 'product:category' category_id=2 %}">ЖЕНСКИЕ</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="fs-6 text-dark text-decoration-none"
                               href="{% url 'product:sort' sort='cheaper' %}">СНАЧАЛО ДЕШЕВЫЕ</a>
                        </li>
                        <li class="list-inline-item">
                            <a class="fs-6 text-dark text-decoration-none"
                               href="{% url 'product:sort' sort='expensive' %}">СНАЧАЛО ДОРОГИЕ</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-md-4">
                    <div class="card text-center mb-4 product-wap rounded-0">
                        <div class="card rounded-0">
                            <img class="card-img rounded-0 img-fluid" src="/media/{{ product.image }}">
                            <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                                <ul class="list-unstyled">
                                    <li><a class="btn btn-success text-white mt-2"
                                           href="{% url 'product:product_details' product.id %}"><i
                                            class="far fa-eye"></i></a></li>
                                    <li><a href="{% url 'product:basket_add' product.id %}"
                                           class="btn btn-success text-white mt-2"><i
                                            class="fas fa-cart-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'product:product_details' product.id %}"
                               class="h3 text-decoration-none text-dark">{{ product.name }}</a>
                            <h5 class="text-center">{{ product.price }} грн.</h5>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %} {% url 'product:page' products.previous_page_number %}{% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Назад</a>
                        </li>
                        {% for page in products.paginator.page.range %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{% url 'product:page' %}">
                                {{page}}
                            </a>
                        </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_next%} {% url 'product:page' products.next_page_number %} {% else %} # {% endif %}">
                                Далее</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container py-5">
    <p class="fs-4 text-center">По запросу: "{{ search }}" ничего не найдено! </p>
</div>

{% endif %}
<!-- End Content -->

<!-- Start Brands -->
<section class="bg-light py-5">
    <div class="container my-4">
        <div class="row text-center py-3">
            <div class="col-lg-6 m-auto">
                <h1 class="h2">Бренды</h1>
            </div>
            <div class="col-lg-9 m-auto tempaltemo-carousel">
                <div class="row d-flex flex-row">
                    <!--Controls-->
                    <div class="col-1 align-self-center">
                        <a class="h1" href="#multi-item-example" role="button" data-bs-slide="prev">
                            <i class="text-light fas fa-chevron-left"></i>
                        </a>
                    </div>
                    <!--End Controls-->

                    <!--Carousel Wrapper-->
                    <div class="col">
                        <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example"
                             data-bs-ride="carousel">
                            <!--Slides-->
                            <div class="carousel-inner" role="listbox">

                                <!--First slide-->
                                <div class="carousel-item active">
                                    <div class="row">
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Rado' %}">
                                                <img class="img-fluid brand-img"
                                                     src="{% static 'assets/img/brand_02.png' %}"
                                                     alt="Brand Logo">
                                            </a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Rolex' %}">
                                                <img class="img-fluid brand-img"
                                                     src="{% static 'assets/img/brand_01.png' %}"
                                                     alt="Brand Logo">
                                            </a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Audemars Piguet' %}">
                                                <img class="img-fluid brand-img"
                                                     src="{% static 'assets/img/brand_03.png' %}"
                                                     alt="Brand Logo">
                                            </a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Patek Philippe' %}">
                                                <img class="img-fluid brand-img"
                                                     src="{% static 'assets/img/brand_04.png' %}"
                                                     alt="Brand Logo">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!--End First slide-->

                                <!--Second slide-->
                                <div class="carousel-item">
                                    <div class="row">
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Omega' %}"><img
                                                    class="img-fluid brand-img"
                                                    src="{% static 'assets/img/brand_05.png' %}"
                                                    alt="Brand Logo"></a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Cartier' %}"><img
                                                    class="img-fluid brand-img"
                                                    src="{% static 'assets/img/brand_06.png' %}"
                                                    alt="Brand Logo"></a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Hublot' %}"><img
                                                    class="img-fluid brand-img"
                                                    src="{% static 'assets/img/brand_07.png' %}"
                                                    alt="Brand Logo"></a>
                                        </div>
                                        <div class="col-3 p-md-5">
                                            <a href="{% url 'product:brand' brand='Longines' %}"><img
                                                    class="img-fluid brand-img"
                                                    src="{% static 'assets/img/brand_08.png' %}"
                                                    alt="Brand Logo"></a>
                                        </div>
                                    </div>
                                </div>
                                <!--End Second slide-->
                            </div>
                            <!--End Slides-->
                        </div>
                    </div>
                    <!--End Carousel Wrapper-->

                    <!--Controls-->
                    <div class="col-1 align-self-center">
                        <a class="h1" href="#multi-item-example" role="button" data-bs-slide="next">
                            <i class="text-light fas fa-chevron-right"></i>
                        </a>
                    </div>
                    <!--End Controls-->
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Brands-->
{% endblock %}


</body>

</html>